name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DBT_PROFILE_TARGET: dev
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}

defaults:
 run:
   working-directory: ci_profiles  # this tells GitHub Actions where to find the profiles.yml for Snowflake connection details

jobs:
  run-and-test:
    name: dbt run and test CI checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Remove existing pipenv environment
      run: pipenv --rm || true
    - name: Install pipfile packages
      run: pipenv install
    - name: Install dbt deps
      run: pipenv run dbt deps
    - name: Build the models
      run: pipenv run dbt build --target dev
