name: Scheduled dbt production run

on:
  schedule:
    - cron: '0 10 * * *' # Run refresh at 10am UTC everyday (6am EST)

env:
  DBT_PROFILE_TARGET: production
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}

defaults:
 run:
   working-directory: ci_profiles

jobs:
  prod:
    name: Scheduled dbt refresh and test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Remove existing pipenv environment
      run: pipenv --rm || true
    - name: Install pipfile packages
      run: pipenv install
    - name: Install dbt deps
      run: pipenv run dbt deps
    - name: Load seed data
      run: pipenv run dbt seed --target production --full-refresh
    - name: Build the models
      run: pipenv run dbt run --target production
    - name: Execute the tests
      run: pipenv run dbt test
