tasks:
  - command: |
      echo "Running the command script"
      mkdir -p /workspace/.dbt
      ln -snf /workspace/.dbt ~/.dbt
      touch profiles.yml
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
vscode:
  extensions:
    - github.vscode-pull-request-github
